FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y vim wget nano 
RUN apt install -y net-tools
RUN apt install -y iputils-ping 
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd


RUN echo 'root:root' |chpasswd

RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config

RUN mkdir /root/.ssh
RUN ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
 
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64
ENV JRE_HOME /usr/lib/jvm/java-8-openjdk-arm64/jre
ENV PATH /opt/hadoop-2.6.5/bin:/opt/hadoop-2.6.5/sbin:/usr/lib/jvm/java-8-openjdk-arm64/bin:$PATH
ENV CLASSPATH ./:/usr/lib/jvm/java-8-openjdk-amd64/lib:/usr/lib/jvm/java-8-openjdk-arm64/jre/lib

WORKDIR /opt 
RUN wget https://archive.apache.org/dist/hadoop/common/hadoop-2.6.5/hadoop-2.6.5.tar.gz
RUN tar -xvzf hadoop-2.6.5.tar.gz

EXPOSE 22

CMD  ["/usr/sbin/sshd", "-D", "&", "/etc/init.d/ssh", "start"]

# need to run hadoop namenode -format